In [ ]:
# !pip install transformers

In [2]:
from transformers import pipeline

In [3]:
chatbot = pipeline("conversational",
                   model = "facebook/blenderbot-400M-distill")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.57k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/730M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/347 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/127k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/62.9k [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/16.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/310k [00:00<?, ?B/s]

In [8]:
user_message = """
Tell about batman
"""
# Need to put this into Conversation object

In [9]:
from transformers import Conversation
conversation = Conversation(user_message)

In [10]:
conversation = chatbot(conversation)

In [11]:
print(conversation)

Conversation id: a46efa5b-4cd3-48aa-9411-2916491a5e2a
user: 
Tell about batman

assistant:  Batman is one of my favorite superheroes. He is an American comic book character.



In [12]:
conversation.add_message({
    "role": "user",
    "content": "Do you have any other favourites?"
})

In [13]:
print(conversation)

Conversation id: a46efa5b-4cd3-48aa-9411-2916491a5e2a
user: 
Tell about batman

assistant:  Batman is one of my favorite superheroes. He is an American comic book character.
user: Do you have any other favourites?



In [14]:
conversation = chatbot(conversation)
print(conversation)

Conversation id: a46efa5b-4cd3-48aa-9411-2916491a5e2a
user: 
Tell about batman

assistant:  Batman is one of my favorite superheroes. He is an American comic book character.
user: Do you have any other favourites?
assistant:  Batman is my favorite. He was created by Bob Kane and Bill Finger in 1939.



In [18]:
# !pip install torch

In [16]:
from transformers import pipeline
import torch

In [20]:
# NLLB - No Language Left Behind
translator = pipeline(task="translation",
                      model="facebook/nllb-200-distilled-600M",
                      torch_dtype=torch.bfloat16)

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/4.85M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/3.55k [00:00<?, ?B/s]

In [32]:
text = """
You are the only star
in the film I never made
"""

In [33]:
# tam_Taml
text_translated = translator(
    text,
    src_lang="eng_Latn",
    tgt_lang="tam_Taml"
)

In [34]:
print(text_translated[0]["translation_text"])

நான் ஒருபோதும் படமாக்காத படத்தில் நீ மட்டுமே நட்சத்திரம் .


In [35]:
# Deleting the model
import gc
del translator
del chatbot
gc.collect()

229

In [37]:
summarizer = pipeline(task="summarization",
                      model="facebook/bart-large-cnn")

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [38]:
text = """
The creation of FLORES-200 doubles the existing language coverage of FLORES-101. Given the nature of the new languages, which have less standardization and require more specialized professional translations, the verification process became more complex. This required modifications to the translation workflow. FLORES-200 has several languages which were not translated from English. Specifically, several languages were translated from Spanish, French, Russian and Modern Standard Arabic. Moreover, FLORES-200 also includes two script alternatives for four languages.
"""

In [39]:
summary = summarizer(text,
                     min_length=10,
                     max_length=100)

In [41]:
print(summary[0]["summary_text"])

FLORES-200 has several languages which were not translated from English. Several languages were translated from Spanish, French, Russian and Modern Standard Arabic.


In [42]:
summary = summarizer(text)
print(summary[0]["summary_text"])

Your max_length is set to 142, but your input_length is only 108. Since this is a summarization task, where outputs shorter than the input are typically wanted, you might consider decreasing max_length manually, e.g. summarizer('...', max_length=54)


FLORES-200 has several languages which were not translated from English. Several languages were translated from Spanish, French, Russian and Modern Standard Arabic. FLORes-200 also includes two script alternatives for four languages. The new languages have less standardization and require more specialized professional translations.


In [43]:
# Deleting the model
import gc
del summarizer
gc.collect()

38

In [45]:
# !pip install sentence-transformers

In [46]:
from sentence_transformers import SentenceTransformer

In [47]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [61]:
sentences1 = [
    "The cat sits outside",
    "A man is playing guitar",
    "The movies are awesome"
]

In [62]:
embeddings1 = model.encode(sentences1, convert_to_tensor=True)
embeddings1

tensor([[ 0.1392,  0.0030,  0.0470,  ...,  0.0641, -0.0163,  0.0636],
        [ 0.0227, -0.0014, -0.0056,  ..., -0.0225,  0.0846, -0.0283],
        [-0.1043, -0.0628,  0.0093,  ...,  0.0020,  0.0653, -0.0150]])

In [69]:
sentences2 = [
    "The dog plays in the hall",
    "A woman is playing cricket",
    "This movie is good"
]

In [70]:
embeddings2 = model.encode(sentences2, convert_to_tensor=True)
embeddings2

tensor([[ 0.0226, -0.0133,  0.0275,  ...,  0.1151,  0.0115,  0.0734],
        [ 0.0154, -0.0006, -0.0494,  ..., -0.0445,  0.0654, -0.0473],
        [-0.0947,  0.0034, -0.0097,  ...,  0.0144,  0.0528,  0.0072]])

In [71]:
# Cosine distance - measure how close/far two vectors are
from sentence_transformers import util
cosine_distance = util.cos_sim(embeddings1, embeddings2)
print(cosine_distance)

tensor([[ 0.2571,  0.0514, -0.0411],
        [ 0.0788,  0.2243,  0.0198],
        [ 0.0053,  0.0022,  0.5729]])


In [72]:
# Deleting the model
import gc
del model
gc.collect()

230